repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/kynan/nbstripout
    rev: 0.9.1
    hooks:
      - id: nbstripout
        args:
          - "--extra-keys=metadata.kernelspec metadata.language_info.codemirror_mode.version metadata.language_info.pygments_lexer metadata.language_info.version metadata.widgets"

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.14
    hooks:
      - id: ruff-check
        args: ["--fix"]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.1.0
    hooks:
      - id: mypy
        args: ["tn4ml/", "--ignore-missing-imports", "--no-strict-optional"]
        pass_filenames: false
        additional_dependencies:
          - numpy
          - types-setuptools

  - repo: https://github.com/PyCQA/bandit
    rev: 1.9.0
    hooks:
      - id: bandit
        args: ["-ll"]
        files: ^tn4ml/
        exclude: ^tn4ml/scipy/
