import warnings

from .embeddings import (
    Embedding,
    FourierEmbedding,
    GaussianRBFEmbedding,
    JaxArraysEmbedding,
    LinearComplementEmbedding,
    PatchAmplitudeEmbedding,
    PatchEmbedding,
    PolynomialEmbedding,
    TrigonometricEmbedding,
    TrigonometricEmbeddingAvg,
    TrigonometricEmbeddingChain,
    embed,
)
from .eval import (
    compare_AUC,
    compare_FPR_per_TPR,
    compare_TPR_per_FPR,
    get_FPR_for_fixed_TPR,
    get_mean_and_error,
    get_precision_recall_curve_data,
    get_roc_curve_data,
    get_TPR_for_fixed_FPR,
    plot_accuracy,
    plot_loss,
    plot_PR_curve,
    plot_ROC_curve_from_data,
    plot_ROC_curve_from_metrics,
)
from .initializers import (
    gramschmidt,
    identity,
    ones,
    rand_unitary,
    randn,
    zeros,
)
from .metrics import (
    CombinedLoss,
    CrossEntropySoftmax,
    CrossEntropyWeighted,
    LogFrobNorm,
    LogPowFrobNorm,
    LogQuadNorm,
    LogReLUFrobNorm,
    MeanSquaredError,
    NegLogLikelihood,
    NoReg,
    OptaxWrapper,
    QuadFrobNorm,
    QuadNorm,
    SemiSupervisedLoss,
    SemiSupervisedNLL,
    Softmax,
    TransformedSquaredNorm,
)
from .strategy import Global, Strategy, Sweeps
from .util import (
    TrainingType,
    divide_into_patches,
    from_dense_to_mps,
    from_mps_to_dense,
    gramschmidt_col,
    gramschmidt_row,
    integer_to_one_hot,
    pad_image_alternately,
    return_digits,
    zigzag_order,
)
